### ISSUE TITLE
Creating new `mx` sessions from within tmux

### ISSUE THREAD

**Issue by yoshuawuyts** [pengwynn/dotfiles#15]
I was wondering what your workflow is to create a new session from within `tmux`. Basically the new-session equivalent of `C-s`. The reason I'm asking is because if the answer is: "quit tmux and create a new session" I'll be creating a PR to add it (see https://github.com/yoshuawuyts/dotfiles/issues/30).

Thanks for your time (and your dotfiles, har har).

**Comment by pengwynn** [comment]
I often do detach, `cd` and then run `mx`. I'd love to see a patch if you've got a better flow.

**Comment by demands** [comment]
I kind of lost track of exactly when / how [my fork of mx](https://github.com/demands/mx) diverged, but it definitely allows you to do this.

**Comment by demands** [comment]
Ah, yep, it [checks to see if you are calling mx from a tmux session](https://github.com/demands/mx/blob/master/bin/mx#L69-L76):

```bash
# Are we in a tmux session?
if [[ -n ${TMUX:-} ]]; then
  inside_tmux_session=1
else
  inside_tmux_session=0
fi
```

and then if you are in one, [it switches clients instead of attaching](https://github.com/demands/mx/blob/master/bin/mx#L179-L183):

```bash
if [[ $inside_tmux_session = 1 ]]; then
  tmux switch-client -t "$session_name"
else
  tmux attach-session -t "$session_name" -c "$session_path"
fi
```

it also [clears out the `$TMUX` variable](https://github.com/demands/mx/blob/master/bin/mx#L72), because otherwise tmux will complain about nested sessions.

Hope this is helpful.

**Comment by yoshuawuyts** [comment]
@demands ooh, that's definitely helpful. Thanks for sharing!

**Comment by yoshuawuyts** [comment]
Nope, actually I don't think there's a better workflow. Tried some things and combined with the `c` command I've already got everything needed. Thanks!
